excluded: # paths to ignore during linting.
  - Pods
  # - Carthage
  - R.generated.swift

disabled_rules:
  - line_length
  - trailing_whitespace
  # - statement_position
  # - force_cast
  # - vertical_whitespace
  # - redundant_string_enum_value
  # - unused_closure_parameter
  - identifier_name

# #rule parameters
# type_name:
#   max_length:
#     warning: 50
#     error: 60
# variable_name:
#   min_length:
#     warning: 1
#     error: 1
#   max_length:
#     warning: 50
#     error: 60
