//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 2 images.
  struct image {
    /// Image `round-swap-horizontal-circle`.
    static let roundSwapHorizontalCircle = Rswift.ImageResource(bundle: R.hostingBundle, name: "round-swap-horizontal-circle")
    /// Image `round-swap-vertical-circle`.
    static let roundSwapVerticalCircle = Rswift.ImageResource(bundle: R.hostingBundle, name: "round-swap-vertical-circle")
    
    /// `UIImage(named: "round-swap-horizontal-circle", bundle: ..., traitCollection: ...)`
    static func roundSwapHorizontalCircle(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.roundSwapHorizontalCircle, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "round-swap-vertical-circle", bundle: ..., traitCollection: ...)`
    static func roundSwapVerticalCircle(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.roundSwapVerticalCircle, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 2 nibs.
  struct nib {
    /// Nib `CurrencyExchangeView`.
    static let currencyExchangeView = _R.nib._CurrencyExchangeView()
    /// Nib `CurrencyView`.
    static let currencyView = _R.nib._CurrencyView()
    
    /// `UINib(name: "CurrencyExchangeView", in: bundle)`
    static func currencyExchangeView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.currencyExchangeView)
    }
    
    /// `UINib(name: "CurrencyView", in: bundle)`
    static func currencyView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.currencyView)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `CurrencyExchange`.
    static let currencyExchange = _R.storyboard.currencyExchange()
    /// Storyboard `CurrencyList`.
    static let currencyList = _R.storyboard.currencyList()
    
    /// `UIStoryboard(name: "CurrencyExchange", bundle: ...)`
    static func currencyExchange(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.currencyExchange)
    }
    
    /// `UIStoryboard(name: "CurrencyList", bundle: ...)`
    static func currencyList(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.currencyList)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 2 localization keys.
    struct localizable {
      /// en translation: Exchange
      /// 
      /// Locales: en
      static let currency_exchange_title = Rswift.StringResource(key: "currency_exchange_title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en"], comment: nil)
      /// en translation: en
      /// 
      /// Locales: en
      static let loc_lang = Rswift.StringResource(key: "loc_lang", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en"], comment: nil)
      
      /// en translation: Exchange
      /// 
      /// Locales: en
      static func currency_exchange_title(_: Void = ()) -> String {
        return NSLocalizedString("currency_exchange_title", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: en
      /// 
      /// Locales: en
      static func loc_lang(_: Void = ()) -> String {
        return NSLocalizedString("loc_lang", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    struct _CurrencyExchangeView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "CurrencyExchangeView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }
      
      fileprivate init() {}
    }
    
    struct _CurrencyView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "CurrencyView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try currencyExchange.validate()
      try currencyList.validate()
    }
    
    struct currencyExchange: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = CurrencyExchangeNavigationController
      
      let bundle = R.hostingBundle
      let currencyExchangeNavigationController = StoryboardViewControllerResource<CurrencyExchangeNavigationController>(identifier: "CurrencyExchangeNavigationController")
      let currencyExchangeViewController = StoryboardViewControllerResource<CurrencyExchangeViewController>(identifier: "CurrencyExchangeViewController")
      let name = "CurrencyExchange"
      
      func currencyExchangeNavigationController(_: Void = ()) -> CurrencyExchangeNavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: currencyExchangeNavigationController)
      }
      
      func currencyExchangeViewController(_: Void = ()) -> CurrencyExchangeViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: currencyExchangeViewController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "round-swap-horizontal-circle") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'round-swap-horizontal-circle' is used in storyboard 'CurrencyExchange', but couldn't be loaded.") }
        if _R.storyboard.currencyExchange().currencyExchangeViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'currencyExchangeViewController' could not be loaded from storyboard 'CurrencyExchange' as 'CurrencyExchangeViewController'.") }
        if _R.storyboard.currencyExchange().currencyExchangeNavigationController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'currencyExchangeNavigationController' could not be loaded from storyboard 'CurrencyExchange' as 'CurrencyExchangeNavigationController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct currencyList: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = CurrencyListNavigationController
      
      let bundle = R.hostingBundle
      let currencyListNavigationController = StoryboardViewControllerResource<CurrencyListNavigationController>(identifier: "CurrencyListNavigationController")
      let currencyListViewController = StoryboardViewControllerResource<CurrencyListViewController>(identifier: "CurrencyListViewController")
      let name = "CurrencyList"
      
      func currencyListNavigationController(_: Void = ()) -> CurrencyListNavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: currencyListNavigationController)
      }
      
      func currencyListViewController(_: Void = ()) -> CurrencyListViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: currencyListViewController)
      }
      
      static func validate() throws {
        if _R.storyboard.currencyList().currencyListNavigationController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'currencyListNavigationController' could not be loaded from storyboard 'CurrencyList' as 'CurrencyListNavigationController'.") }
        if _R.storyboard.currencyList().currencyListViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'currencyListViewController' could not be loaded from storyboard 'CurrencyList' as 'CurrencyListViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
